import { Agendamento, Fisioterapeuta, Paciente } from "./types";

export const FISIOTERAPEUTAS: Fisioterapeuta[] = [
  {
    id: "f1",
    nome: "Dra. Ana Lima",
    especialidade: "Ortopedia e Esportes",
    cor: "#0F6E56",
  },
  {
    id: "f2",
    nome: "Dr. Carlos Souza",
    especialidade: "Neurologia",
    cor: "#185FA5",
  },
  {
    id: "f3",
    nome: "Dra. Fernanda Melo",
    especialidade: "Pilates e RPG",
    cor: "#993C1D",
  },
];

export const PACIENTES: Paciente[] = [
  {
    id: "p1",
    nome: "João Pereira",
    telefone: "(65) 99801-2345",
    email: "joao@email.com",
    dataNascimento: "1985-03-12",
    convenio: "Unimed",
  },
  {
    id: "p2",
    nome: "Maria Oliveira",
    telefone: "(65) 99712-3456",
    email: "maria@email.com",
    dataNascimento: "1992-07-25",
    convenio: "Bradesco",
  },
  {
    id: "p3",
    nome: "Carlos Rodrigues",
    telefone: "(65) 99623-4567",
    email: "carlos@email.com",
    dataNascimento: "1978-11-08",
    convenio: "SulAmérica",
  },
  {
    id: "p4",
    nome: "Ana Paula Santos",
    telefone: "(65) 99534-5678",
    email: "ana@email.com",
    dataNascimento: "1990-01-15",
  },
  {
    id: "p5",
    nome: "Roberto Fernandes",
    telefone: "(65) 99445-6789",
    email: "roberto@email.com",
    dataNascimento: "1965-09-30",
    convenio: "Unimed",
  },
  {
    id: "p6",
    nome: "Luciana Costa",
    telefone: "(65) 99356-7890",
    email: "luciana@email.com",
    dataNascimento: "1995-05-20",
    convenio: "Amil",
  },
  {
    id: "p7",
    nome: "Paulo Mendes",
    telefone: "(65) 99267-8901",
    email: "paulo@email.com",
    dataNascimento: "1982-12-03",
  },
  {
    id: "p8",
    nome: "Beatriz Alves",
    telefone: "(65) 99178-9012",
    email: "beatriz@email.com",
    dataNascimento: "1998-08-17",
    convenio: "Bradesco",
  },
];

function getMonday(date: Date): Date {
  const d = new Date(date);
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  d.setDate(diff);
  return d;
}

function addDays(date: Date, days: number): string {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

const today = new Date();
const monday = getMonday(today);

export const AGENDAMENTOS: Agendamento[] = [
  // Segunda
  {
    id: "a1",
    pacienteId: "p1",
    paciente: PACIENTES[0],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 0),
    horaInicio: "08:00",
    horaFim: "08:50",
    tipoSessao: "Fisioterapia Ortopédica",
    status: "confirmado",
    sessaoNumero: 3,
    totalSessoes: 10,
    observacoes: "Dor lombar crônica, exercícios de core.",
  },
  {
    id: "a2",
    pacienteId: "p3",
    paciente: PACIENTES[2],
    fisioterapeutaId: "f2",
    fisioterapeuta: FISIOTERAPEUTAS[1],
    data: addDays(monday, 0),
    horaInicio: "09:00",
    horaFim: "09:50",
    tipoSessao: "Fisioterapia Neurológica",
    status: "confirmado",
    sessaoNumero: 5,
    totalSessoes: 20,
  },
  {
    id: "a3",
    pacienteId: "p5",
    paciente: PACIENTES[4],
    fisioterapeutaId: "f3",
    fisioterapeuta: FISIOTERAPEUTAS[2],
    data: addDays(monday, 0),
    horaInicio: "10:00",
    horaFim: "10:50",
    tipoSessao: "Pilates Clínico",
    status: "pendente",
    sessaoNumero: 1,
    totalSessoes: 12,
  },
  {
    id: "a4",
    pacienteId: "p2",
    paciente: PACIENTES[1],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 0),
    horaInicio: "14:00",
    horaFim: "14:50",
    tipoSessao: "Avaliação Inicial",
    status: "confirmado",
  },
  // Terça
  {
    id: "a5",
    pacienteId: "p4",
    paciente: PACIENTES[3],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 1),
    horaInicio: "08:00",
    horaFim: "08:50",
    tipoSessao: "RPG",
    status: "confirmado",
    sessaoNumero: 7,
    totalSessoes: 10,
  },
  {
    id: "a6",
    pacienteId: "p6",
    paciente: PACIENTES[5],
    fisioterapeutaId: "f2",
    fisioterapeuta: FISIOTERAPEUTAS[1],
    data: addDays(monday, 1),
    horaInicio: "09:00",
    horaFim: "09:50",
    tipoSessao: "Fisioterapia Neurológica",
    status: "cancelado",
    sessaoNumero: 3,
    totalSessoes: 15,
  },
  {
    id: "a7",
    pacienteId: "p7",
    paciente: PACIENTES[6],
    fisioterapeutaId: "f3",
    fisioterapeuta: FISIOTERAPEUTAS[2],
    data: addDays(monday, 1),
    horaInicio: "11:00",
    horaFim: "11:50",
    tipoSessao: "Pilates Clínico",
    status: "confirmado",
    sessaoNumero: 4,
    totalSessoes: 12,
  },
  // Quarta
  {
    id: "a8",
    pacienteId: "p8",
    paciente: PACIENTES[7],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 2),
    horaInicio: "08:00",
    horaFim: "08:50",
    tipoSessao: "Fisioterapia Ortopédica",
    status: "confirmado",
    sessaoNumero: 2,
    totalSessoes: 8,
  },
  {
    id: "a9",
    pacienteId: "p1",
    paciente: PACIENTES[0],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 2),
    horaInicio: "09:00",
    horaFim: "09:50",
    tipoSessao: "Fisioterapia Ortopédica",
    status: "confirmado",
    sessaoNumero: 4,
    totalSessoes: 10,
  },
  {
    id: "a10",
    pacienteId: "p3",
    paciente: PACIENTES[2],
    fisioterapeutaId: "f2",
    fisioterapeuta: FISIOTERAPEUTAS[1],
    data: addDays(monday, 2),
    horaInicio: "14:00",
    horaFim: "14:50",
    tipoSessao: "Fisioterapia Neurológica",
    status: "pendente",
    sessaoNumero: 6,
    totalSessoes: 20,
  },
  // Quinta
  {
    id: "a11",
    pacienteId: "p2",
    paciente: PACIENTES[1],
    fisioterapeutaId: "f3",
    fisioterapeuta: FISIOTERAPEUTAS[2],
    data: addDays(monday, 3),
    horaInicio: "08:00",
    horaFim: "08:50",
    tipoSessao: "Pilates Clínico",
    status: "confirmado",
    sessaoNumero: 2,
    totalSessoes: 12,
  },
  {
    id: "a12",
    pacienteId: "p5",
    paciente: PACIENTES[4],
    fisioterapeutaId: "f1",
    fisioterapeuta: FISIOTERAPEUTAS[0],
    data: addDays(monday, 3),
    horaInicio: "10:00",
    horaFim: "10:50",
    tipoSessao: "Fisioterapia Ortopédica",
    status: "concluido",
    sessaoNumero: 1,
    totalSessoes: 8,
  },
  // Sexta
  {
    id: "a13",
    pacienteId: "p6",
    paciente: PACIENTES[5],
    fisioterapeutaId: "f2",
    fisioterapeuta: FISIOTERAPEUTAS[1],
    data: addDays(monday, 4),
    horaInicio: "09:00",
    horaFim: "09:50",
    tipoSessao: "Acupuntura",
    status: "confirmado",
    sessaoNumero: 2,
    totalSessoes: 6,
  },
  {
    id: "a14",
    pacienteId: "p4",
    paciente: PACIENTES[3],
    fisioterapeutaId: "f3",
    fisioterapeuta: FISIOTERAPEUTAS[2],
    data: addDays(monday, 4),
    horaInicio: "10:00",
    horaFim: "10:50",
    tipoSessao: "RPG",
    status: "pendente",
    sessaoNumero: 8,
    totalSessoes: 10,
  },
];
